// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMuJPKUgkIbCyg3ZKVELAu5tHHGEUt5Q',
    appId: '1:108517738544:web:33592a135ce2b8995545f5',
    messagingSenderId: '108517738544',
    projectId: 'juviapp-c37c1',
    authDomain: 'juviapp-c37c1.firebaseapp.com',
    storageBucket: 'juviapp-c37c1.appspot.com',
    measurementId: 'G-FPHTQBS4CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOP8zR3BTUdhYMNsw6BhpNEMTAmtO2dOY',
    appId: '1:108517738544:android:19824fdfef89c34e5545f5',
    messagingSenderId: '108517738544',
    projectId: 'juviapp-c37c1',
    storageBucket: 'juviapp-c37c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArfZMzPyHOMwVupvaUQxdZcdgtMhfWQPk',
    appId: '1:108517738544:ios:764254745b681f5c5545f5',
    messagingSenderId: '108517738544',
    projectId: 'juviapp-c37c1',
    storageBucket: 'juviapp-c37c1.appspot.com',
    iosClientId: '108517738544-vo65kto3gnqt1een3g31mbdns7iiv02t.apps.googleusercontent.com',
    iosBundleId: 'com.example.garantia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArfZMzPyHOMwVupvaUQxdZcdgtMhfWQPk',
    appId: '1:108517738544:ios:764254745b681f5c5545f5',
    messagingSenderId: '108517738544',
    projectId: 'juviapp-c37c1',
    storageBucket: 'juviapp-c37c1.appspot.com',
    iosClientId: '108517738544-vo65kto3gnqt1een3g31mbdns7iiv02t.apps.googleusercontent.com',
    iosBundleId: 'com.example.garantia',
  );
}
